// keys
export const CMDB_RECENTLY_ADDED = "CMDB_RECENTLY_ADDED";
export const CMDB_FETCH_BOOKMARKS = "CMDB_FETCH_BOOKMARKS";
export const CMDB_FETCH_RECENT_BOOKMARKS = "CMDB_FETCH_RECENT_BOOKMARKS";
export const SEARCH_RESULT = "search_result";
export const CMDB_CREATE_BOOKMARK = "CMDB_CREATE_BOOKMARK";
export const CMDB_SEARCH = "CMDB_SEARCH";
export const CMDB_DELETE_BOOKMARK = "CMDB_DELETE_BOOKMARK";
